# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Math Utility .Net CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Collect build outputs
      run: |
        mkdir -p output
        cp **/bin/Debug/net8.0/*.exe output/
        cp **/bin/Debug/net8.0/*.dll output/

    - name: Upload build outputs
      uses: actions/upload-artifact@v2
      with:
        name: build-outputs
        path: output  
